server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file:///Users/nhn/document/spring-cloud-yaml-repo
          uri: https://github.com/anstjaos/spring-cloud-yaml-repo
          default-label: master
